sudo: required
services:
    - docker

before_install:
    - docker build -t ivanaverin/docker-react -f Dockerfile.dev .

script:
    - docker run ivanaverin/docker-react npm run test -- --coverage